### ISSUE TITLE
Small holes where caves do not break through surface

### ISSUE THREAD

**Issue by BloodlessBaron** [superfluke/WorleyCaves#13]
I'm having the problem where caves that come close to the surface leave this distinctive grid pattern of 1x1 holes that bore down several blocks until they break through to the caves. This happens any time I use the mod alongside mods that change the world gen, specifically Biomes O' Plenty and/or BiomeTweaker. I've tried it with just Worley Caves and either of those mods installed, and the problem was reproduced both times.

![2018-11-30_01 50 52](https://user-images.githubusercontent.com/40747083/49275889-67207780-f442-11e8-88f7-1ba4e15734e7.png)

![2018-11-30_00 47 52](https://user-images.githubusercontent.com/40747083/49275628-794de600-f441-11e8-84b5-054ee760fcf0.png)

**Comment by superfluke** [comment]
Sorry it took so long to get back to, thank for the detailed reports.
