### ISSUE TITLE
just an idea that would hopefully be easy to do

### ISSUE THREAD

**Issue by Redd56** [superfluke/WorleyCaves#15]
so maybe if it detects the world type as being a cubic chunks enabled one it allows the caves to generate at all depths below y0 also, and a new lava system would be present for the caves full of lava, like below y 64 theres a 2nd seeded system with lava caves that are much more rare
i8dk just an idea

**Comment by superfluke** [comment]
added some lava configs is 1.4.0
cubic chunks duplicate #11
