### ISSUE TITLE
Biome Bundle

### ISSUE THREAD

**Issue by Oraiz** [superfluke/WorleyCaves#16]
I've made a small custom pack, and have used Biome Bundle for my world gen, but also included Worley's Caves as I wanted a more expansive underground. However caves are seemingly unaffected!
Both mods have default configs, and as far as I know, there is no other mod that would change terrain generation (all I can think is Quark's realistic, which I've turned off).

Any help would be appreciated, and I can provide any other details that might help.

Thanks in advance.

**Comment by superfluke** [comment]
Biome bundle overrides caves with their own more configurable version of vanilla caves. You can try opening an issue with them to see if they would be willing to add a config that would let other mods take over the cave generation. Not much I can do on my side.

**Comment by Oraiz** [comment]
Thank you very much for the quick reply. I've opened the same issue on their git, so hopefully get a reply soon.

I had seen a couple of people on reddit saying they had the two working together (without any config changes), so I thought maybe there was something I was or wasn't doing right! I'll let you know if they say anything about it. :)
