### ISSUE TITLE
Request: Compat between worley and Subterranean Waters

### ISSUE THREAD

**Issue by edenhack** [superfluke/WorleyCaves#17]
Merely giving this a shot but would it be possible to have these intermesh each other in some way? I love worleys caves for the intense large caves they build that are great for Trolls and other modded mobs to inhabit. But I also like sub waters for an interesting twist on gathering rare resources.

**Comment by superfluke** [comment]
The two mods do work together, or did you mean something else

**Comment by edenhack** [comment]
Odd it seems to generate large floating patches of water. Is it likely it works best under default settings?Sent from my Sprint Samsung Galaxy Note9.
-------- Original message --------From: superfluke <notifications@github.com> Date: 4/15/19  9:15 PM  (GMT-06:00) To: superfluke/WorleyCaves <WorleyCaves@noreply.github.com> Cc: Eden Hack <nathancbright@gmail.com>, Author <author@noreply.github.com> Subject: Re: [superfluke/WorleyCaves] Request: Compat between worley and Subterranean Waters (#17) The two mods do work together, or did you mean something else

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/superfluke/WorleyCaves","title":"superfluke/WorleyCaves","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/superfluke/WorleyCaves"}},"updates":{"snippets":[{"icon":"PERSON","message":"@superfluke in #17: The two mods do work together, or did you mean something else"}],"action":{"name":"View Issue","url":"https://github.com/superfluke/WorleyCaves/issues/17#issuecomment-483484612"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/superfluke/WorleyCaves/issues/17#issuecomment-483484612",
"url": "https://github.com/superfluke/WorleyCaves/issues/17#issuecomment-483484612",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by superfluke** [comment]
I see what you mean, I'll take a look

**Comment by superfluke** [comment]
I've added additional checks, which helps a bet but isn't a perfect fix. Not sure how to fix all the floating water without wrecking the performance. Currently the problem is made worse by a bug in subterranean water that causes the underground lakes to cut off on chunk borders, not sure if that mod is still being worked on.

**Comment by edenhack** [comment]
Sadly it isn't I believe but its features are exceptionally interesting to play with for cave generation on top of worley caves. Thanks for looking into this as much as you did. I will enjoy it to the fullest I can.Sent from my Sprint Samsung Galaxy Note9.
-------- Original message --------From: superfluke <notifications@github.com> Date: 4/17/19  1:37 PM  (GMT-06:00) To: superfluke/WorleyCaves <WorleyCaves@noreply.github.com> Cc: Eden Hack <nathancbright@gmail.com>, Author <author@noreply.github.com> Subject: Re: [superfluke/WorleyCaves] Request: Compat between worley and Subterranean Waters (#17) I've added additional checks, which helps a bet but isn't a perfect fix. Not sure how to fix all the floating water without wrecking the performance. Currently the problem is made worse by a bug in subterranean water that causes the underground lakes to cut off on chunk borders, not sure if that mod is still being worked on.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/superfluke/WorleyCaves","title":"superfluke/WorleyCaves","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/superfluke/WorleyCaves"}},"updates":{"snippets":[{"icon":"PERSON","message":"@superfluke in #17: I've added additional checks, which helps a bet but isn't a perfect fix. Not sure how to fix all the floating water without wrecking the performance. Currently the problem is made worse by a bug in subterranean water that causes the underground lakes to cut off on chunk borders, not sure if that mod is still being worked on. "}],"action":{"name":"View Issue","url":"https://github.com/superfluke/WorleyCaves/issues/17#issuecomment-484211275"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/superfluke/WorleyCaves/issues/17#issuecomment-484211275",
"url": "https://github.com/superfluke/WorleyCaves/issues/17#issuecomment-484211275",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
