### ISSUE TITLE
Worley's Caves in Beta+ World Type

### ISSUE THREAD

**Issue by Noxalas** [superfluke/WorleyCaves#19]
I was using Beta+ as the generation type and noticed it wasn't compatible with the cave generation. Is there any way of fixing this by myself, or is this a feature either you or the author of that mod has to implement?

I love this mod. Would be awesome to use this alongside Beta+

**Comment by superfluke** [comment]
That would be up to the Beta+ dev. Taking a quick look at his 1.12.2 code, it seems like it should be a fairly easy change to allow for other cave mods to work with it. I would throw this up on their issue tracker.
