### ISSUE TITLE
Compatibility Between Underground Biomes, BiomeTweaker, and WorleyCaves

### ISSUE THREAD

**Issue by xlea99** [superfluke/WorleyCaves#20]
These caves look so fantastic, and I'm currently working on a modpack based around Advanced Rocketry filled with different planets. I want the planets to feel different, so I was excited to use WorleyCaves to get rid of those boring vanilla caves and liven things up a little. However on one of these planets, I used the BiomeTweaker command registerGenBlockRep(schist from UndergroundBiomes) to turn the whole planet into schist instead of vanilla stone. However, when I do this, the WorleyCaves stop spawning in. 

If I make BiomeTweaker do this on PRE_INIT, WorleyCaves just overrides BiomeTweaker and the whole world becomes vanilla minecraft stone again. However, if I make Biometweaker do this on INIT, the whole world turns to schist but there are no caves at all. 

I was just wondering if you had any idea why this would be happening, or if there is any workaround? Thanks a bunch!!

**Comment by MuteTiefling** [comment]
Working on a similar project. If you want the entire stone portion of the world to be replaced with schist, you need to change the filler block for the biome in BiomeTweaker. All of these extra features require minecraft stone to spawn in. But if you force the actual filler block to be something other than stone, then these features continue to work as if it were stone. Same deal for ore generation, etc.

```
filler = forBlock("minecraft:packed_ice")
top = forBlock("minecraft:snow")
myBiomes = forBiomes("biometweaker:myBiome1","biometweaker:myBiome2")
myBiomes.set("topBlock", top)
myBiomes.set("fillerBlock", filler)
myBiomes.addActualFillerBlock(filler)
```

**Comment by superfluke** [comment]
Version 1.5.0 should be more flexible about what type of blocks it can dig through now
