### ISSUE TITLE
Request for feature - control water / lava pockets that form in caves 

### ISSUE THREAD

**Issue by MuteTiefling** [superfluke/WorleyCaves#21]
I'm specifically referring to those lone source blocks of water and lava that generate and flow out into the caves.

I'd love the ability to control what block is used for this so I can use another fluid, or disable them entirely by filling them with stone or air. 

Would something like this be possible? Or is there another mod that can already do this?

**Comment by superfluke** [comment]
The mod SomeLikeItDry has a simple config for disabling the waterfalls in caves (you can disable the other water modifications that mod does). I think BiomeTweaker offers a bit more flexability in switching out blocks or disabling those falls. Specifically you'd want to look at the LAKE_WATER and LAKE_LAVA decorations in the removeDecoration command. Let me know how that works out

**Comment by MuteTiefling** [comment]
@superfluke I ... I could absolutely kiss you right now. LAKE_WATER and LAKE_LAVA did the trick! I never would have guessed these were responsible for these very non lake like features.

Thank you for the assistance and prompt reply!
