### ISSUE TITLE
[1.5.0] Lava level cut up by stone layers

### ISSUE THREAD

**Issue by Compegen** [superfluke/WorleyCaves#23]
In the lava level, every-other level is stone instead of lava.
Not present in 1.4.1

Screenshot's lava level set to y: 20
![2019-09-07_17 56 58](https://user-images.githubusercontent.com/8009507/64481039-a0d49a80-d199-11e9-8715-5dab567ff574.png)

**Comment by superfluke** [comment]
whoops
