### ISSUE TITLE
Dooglamoo worlds compatibility

### ISSUE THREAD

**Issue by blocks119** [superfluke/WorleyCaves#24]
Bacially i'm making a modpack and I am using Dooglamoo worlds as the main terrain generator , unfortunately by default dooglamoo worlds removes vanilla caves and doesnt allow worley's caves to generate , do you have any idea how i might go about making them compatible? or do you have any other possible ways to add caves in ?

I'd appreciate any suggestions

- blocks119

**Comment by superfluke** [comment]
Worley's Caves works with the standard forge cave event. It would be up to the Dooglamoo dev to allow other cave generator to take over. The mod isn't open source so I can't exactly make a pull request to them either, you'd have to open an issue on their mod page. I can't think of any way to force my cave gen to run while using their world type.
