### ISSUE TITLE
Buggy Underground Chunks Generation With SubterreanWaters

### ISSUE THREAD

**Issue by ChrissPz** [superfluke/WorleyCaves#26]
When I Generate a World with Worleys caves generation and SubterreanWaters mod the underground generation it's very buggy and it looks like this

![2019-11-02_01 48 10](https://user-images.githubusercontent.com/33664951/68066823-d373bd00-fd1c-11e9-8e3a-1a53d64b18a5.png)

![2019-11-02_01 49 26](https://user-images.githubusercontent.com/33664951/68066844-42511600-fd1d-11e9-9205-3a4282cbe330.png)

I hope it adds support with SubterreanWaters generation, pls.

**Comment by superfluke** [comment]
SubterreanWaters no longer being developed
