### ISSUE TITLE
Does this work with Terraforged worlds?

### ISSUE THREAD

**Issue by Mcmanybucks** [superfluke/WorleyCaves#28]
Terraforge only seems to affect the overworld and like 3-5 layers down, so I wasn't sure.

**Comment by booleanbyte** [comment]
As far as I'm aware Terraforged is only available for 1.15, which Worley's hasn't been update for at this time, so this isn't really even a a possible issue at this point as far as I can see.

**Comment by Mcmanybucks** [comment]
> 
> 
> As far as I'm aware Terraforged is only available for 1.15, which Worley's hasn't been update for at this time, so this isn't really even a a possible issue at this point as far as I can see.

Oh, right. 

Well, in that case, *will* it be compatible?

**Comment by booleanbyte** [comment]
Well, since Worley's Caves has been ported to 1.15.2 now I can go one further than saying whether it will be compatible, and instead confirm that it is compatible.

**Comment by superfluke** [comment]
Note that by default the caves only generate to y-128. You may want to set it higher in the configs when using terraforged.
