### ISSUE TITLE
Caves "breaking through" surface

### ISSUE THREAD

**Issue by Endgineer** [superfluke/WorleyCaves#3]
Caves seem to break through mountains or the surface; I've seen a few people briefly point this out but then they seem to just go MIA. I think the issue boils down to caves attempting to reach the surface in some way. Some information about how I configured the mod:
1. Set the noiseCutoffValue to -0.36 because I wanted larger caves (caverns).
2. Changed easeInDepth to 30 hoping that caverns would generate deeper in order to avoid expected terrain breakages.

The problem seems to be that the mod always seems to "try to reach the surface". I mistakenly thought that the easeInDepth works as a sharp modifier that only enables cave gen below a certain depth. To verify, I retested with noiseCutoffValue at -0.90 and easeInDepth at 40. The result was as expected- something that looks like the nether below the surface. But the problem is, it does indeed seem that the mod "tries to reach the surface". With these extreme settings, the surface broke even more (see pic)- rivers, mountains, and other places suffered huge tears. The "lower the settings", the less the tears, but they definitely still happened.

![break](https://user-images.githubusercontent.com/6738450/44790181-aa7df800-ab6c-11e8-963a-37e4be1ae64d.png)

It seems like the easeInDepth (judging by the wording) was intended to work like this. I suggest that maybe an extra config option to strictly start cave generation below (and never above) a certain depth would be nice.

**Comment by superfluke** [comment]
Thanks for the detailed report. You're correct, the caves always try to reach the surface. Right now the cut off level at the surface is the normal cutoff level +50%. The cutoff level is reduced over the easeInDepth until it reaches the normal cutoff level. So yes, if you set the cutoff crazy low, like -0.9, then the cutoff at the surface will be -0.45.

I think the best solution might be to make the surface cutoff a separate config option, so users can decide how much the caves break through.

**Comment by Endgineer** [comment]
That definitely sounds like a best solution. The normal cutoff level doesn't do it for larger caves and the tears are pretty much the only thing stopping me from replacing the annoying dead-ended vanilla cave systems. =_=

**Comment by superfluke** [comment]
Version 1.2.0 is up with the new surfaceCutoffValue config. Setting it to 1.0 will make sure no caves break the surface block. If you crank it up to something like 25.0 then you should have no caves through the entire easeInDepth (assuming the easeInDepth is set to 15).
