### ISSUE TITLE
[1.16.1] NPE in setWorldSeed

### ISSUE THREAD

**Issue by Vaelzan** [superfluke/WorleyCaves#33]
So, I know you've already commented on how ugly this line is, but it turns out that it's also causing a null pointer exception when connecting to a dedicated server, at least in our setup trying to add the mod to Valhelsia 3:

https://github.com/superfluke/WorleyCaves/blob/505ff086409c1ca096d8563a62af78f5f3692b10/src/main/java/fluke/worleycaves/proxy/CommonProxy.java#L136

Client debug log w/ exception:
https://gist.github.com/Vaelzan/7ae5806481733b0c7f93bc9ddb5a82e6

**Comment by superfluke** [comment]
Should be smoothed out now, thanks for the report.
