### ISSUE TITLE
Caves still tearing mountains

### ISSUE THREAD

**Issue by Endgineer** [superfluke/WorleyCaves#4]
Using "worleycaves-1.2.0" in modded MC with "easeInDepth=25", "noiseCutoffValue=-0.36", and "surfaceCutoffValue=1.0". It seems like the 1.2.0 patch fixed almost everything; there are zero tears in flat terrain, rivers, oceans, etc.

However, with mountains that go above a certain altitude (such as ones added by BiomesOPlenty), this happens:

![ses1](https://user-images.githubusercontent.com/6738450/44824554-39722b00-abd4-11e8-8669-487c1f931310.png)

I confirmed this by testing the mod alone using the vanilla amplified generation to create huge mountains and then over 3 different worlds using BiomesOPlenty. I'm assuming this happens because the mod "searches for the surface" and then generates caves a certain depth below that surface. Of course this works with mild terrain, but it fails with huge mountains, since their "surface" is high up; the caves generate on the same level as ground level and cause weird holes on the sides and in some cases break into the sides of rivers. I don't know if something like a y-level limit could be implemented, so caves in mountains can be manually disabled by users.

This doesn't happen with small "hills" or smaller mountains, just higher ones (assuming that it's because of how I set the easeInDepth to 25 and surfaceCutoffValue to 1). I also tested this with surfaceCutoffValue at 25 and easeInDepth at 15, just to make sure that I didn't have faulty settings or something.

Amplified Terrain Result:
![ses2](https://user-images.githubusercontent.com/6738450/44825156-43e1f400-abd7-11e8-922e-fb026a4e4b79.png)

It would be nice to have some config option to disable caves above a certain height or something. Even when the caves are small, the cave generation within mountains often creates strange tears and often even breaks into nearby rivers. :/

**Comment by Endgineer** [comment]
This doesn't happen with small "hills" or smaller mountains, just higher ones (because of how I set the easeInDepth to 25 and surfaceCutoffValue to 1).

**Comment by Endgineer** [comment]
Amplified Terrain Result:
![ses2](https://user-images.githubusercontent.com/6738450/44825156-43e1f400-abd7-11e8-922e-fb026a4e4b79.png)

The problem is just that when larger caves generate within mountains, they cause a mess. It would be nice to have some way to disable caves above a certain height or somehow stop them from behaving this way. :/

**Comment by superfluke** [comment]
I wouldn't say it fails with large cliff, that's how it was intended to work, making caves into the sides of cliffs. I can add a config option for max y level though and I do need to improve how water is tested for in those situations so it doesn't cut into the river like that.

**Comment by Endgineer** [comment]
Yeah, I figured. Vanilla MC does the same thing as well (making caves in mountains). By "fails" I meant large caves fail to work as the small ones would (they look very out of place).

A config option for max y would be great. Thanks for making this amazing mod by the way; it's a must have for miners.

**Comment by superfluke** [comment]
Yw, glad to see people enjoying the mod. Version 1.2.1 has the max y level config.
