### ISSUE TITLE
Configs reset to default everytime I restart Minecraft

### ISSUE THREAD

**Issue by crazyirishwrencher** [superfluke/WorleyCaves#6]
Config changes seem to persist until I exit minecraft and restart - then they are set back to default values.

**Comment by crazyirishwrencher** [comment]
Making the changes in notepad and setting the file as read only causes config changes to persist across game restarts.

**Comment by superfluke** [comment]
Whoops, surprised I never noticed this, thanks for the report. Fixed in version 1.2.2, with the bonus that you don't need to restart the game for the config changes to take effect.
