### ISSUE TITLE
Tons of Dirt Patches on the Surface with some cutouts.

### ISSUE THREAD

**Issue by KaneHart** [superfluke/WorleyCaves#7]
1.2.2 Fresh Config No other mods.

I'm finding a lot of not so friendly looking dirt patches when exploring the world. Sadly it seems that the cave system causing this and peaking out the top surface.

Linked a couple of examples:
https://i.imgur.com/DKoUoMP.png
https://i.imgur.com/fKKMr0l.png
https://i.imgur.com/v4w6D3q.png

**Comment by superfluke** [comment]
Fixed in 1.3.0
